"""Export the selected checkpoint and verify Core ML against PyTorch.

Preprocessing is identical to training, offline and covers ALL OCR windows.
The generated judgments are development diagnostics for the Swift grounder;
they are not predictions generated by Qwen or a human acceptance result.
"""
import argparse
import json
import platform
import re
import shutil
import time
from pathlib import Path

import coremltools as ct
import numpy as np
import torch
from transformers import AutoTokenizer
from train_classifier import CLASSES, LENGTH, SCHEDULE_KINDS, ScreenshotClassifier, digest, encode_document, write


def scene(prediction, raw):
    category=prediction["predicted"]
    if category=="ignored": return {"category":"无关","arrangement":"无"}
    if category=="collection": return {"category":"参考收藏","arrangement":"参考"}
    if category=="pickup": return {"category":"领取通知","arrangement":"无"}
    if category=="schedule": return {"category":"明确安排","arrangement":{"confirmed":"确认","travel":"行程","notice":"通知"}[prediction["arrangement"]]}
    # The learned head predicts the four product groups. Literal transaction
    # subtype labels only guide existing evidence verification, never invent fields.
    kind="付款凭证" if re.search(r"支付成功|转账成功|付款成功",raw) else "其他凭证" if re.search(r"兑换券|发票|凭证编号|合同编号",raw) else "已有订单"
    return {"category":kind,"arrangement":"无"}


def main():
    ap=argparse.ArgumentParser();ap.add_argument("--dataset",required=True);ap.add_argument("--base",required=True);ap.add_argument("--run",required=True)
    args=ap.parse_args();root=Path(args.run)
    config=json.loads((root/"configuration.json").read_text())
    assert digest(args.dataset)==config["datasetSha256"]
    torch.set_num_threads(6)
    model=ScreenshotClassifier(args.base,pretrained=False).eval()
    checkpoint=torch.load(root/"best.pt",map_location="cpu",weights_only=True);model.load_state_dict(checkpoint["state_dict"])
    tokenizer=AutoTokenizer.from_pretrained(root/"tokenizer",local_files_only=True)
    examples=(torch.zeros((1,LENGTH),dtype=torch.long),torch.ones((1,LENGTH),dtype=torch.long),torch.zeros((1,LENGTH,5)))
    traced=torch.jit.trace(model,examples)
    converted=ct.convert(traced,convert_to="mlprogram",minimum_deployment_target=ct.target.iOS17,compute_precision=ct.precision.FLOAT16,
        inputs=[ct.TensorType(name="input_ids",shape=(1,LENGTH),dtype=np.int32),ct.TensorType(name="attention_mask",shape=(1,LENGTH),dtype=np.int32),ct.TensorType(name="geometry",shape=(1,LENGTH,5),dtype=np.float32)],
        outputs=[ct.TensorType(name="category_logits"),ct.TensorType(name="arrangement_logits")])
    converted.author="Sift development / assistant-reviewed dataset"
    converted.short_description="Offline Chinese OCR and layout classification; development candidate, not independent acceptance"
    converted.user_defined_metadata.update({"base":"hfl/rbt3","base_revision":config["revision"],"dataset_sha256":config["datasetSha256"],"preprocessing":"Vision bottom-left boxes -> stable 0.015 reading bands; WordPiece; length 256 stride 192; mean window logits","classes":json.dumps(CLASSES),"schedule_kinds":json.dumps(SCHEDULE_KINDS),"human_confirmed":"false"})
    package=root/"SiftScreenshotClassifier.mlpackage";converted.save(str(package))
    torch_predictions={p["id"]:p for p in json.loads((root/"predictions.json").read_text())}
    rows=json.loads(Path(args.dataset).read_text());predictions=[];max_error=0.;agreements=0;arr_agreements=0
    # Core ML prediction triggers model compilation and actual local inference.
    started=time.perf_counter()
    for row in rows:
        features=encode_document(row["document"],tokenizer);cat=[];arr=[];start=time.perf_counter()
        for i in range(features["windows"]):
            result=converted.predict({"input_ids":features["input_ids"][i:i+1].numpy().astype(np.int32),"attention_mask":features["attention_mask"][i:i+1].numpy().astype(np.int32),"geometry":features["geometry"][i:i+1].numpy()})
            cat.append(np.asarray(result["category_logits"]).reshape(5));arr.append(np.asarray(result["arrangement_logits"]).reshape(3))
        logits=np.mean(cat,axis=0);arrlogits=np.mean(arr,axis=0)
        probabilities=np.exp(logits-np.max(logits));probabilities/=probabilities.sum()
        label=int(np.argmax(logits));nature=SCHEDULE_KINDS[int(np.argmax(arrlogits))] if label==2 else "reference" if label==4 else "none"
        reference=torch_predictions[row["id"]]
        max_error=max(max_error,float(np.max(np.abs(logits-np.asarray(reference["logits"])))))
        agreements+=CLASSES[label]==reference["predicted"];arr_agreements+=nature==reference["arrangement"]
        predictions.append({"id":row["id"],"split":row["split"],"expected":row["category"],"predicted":CLASSES[label],"arrangement":nature,"probabilities":probabilities.tolist(),"seconds":time.perf_counter()-start,"windows":features["windows"]})
        if len(predictions)%20==0: print("Core ML",len(predictions),"/",len(rows),flush=True)
    write(root/"coreml-predictions.json",predictions)
    judgments={p["id"]:scene(p,next(r["document"]["rawText"] for r in rows if r["id"]==p["id"])) for p in predictions}
    write(root/"coreml-judgments.json",judgments)
    summary={"samples":len(rows),"categoryAgreementWithPyTorch":agreements,"arrangementAgreementWithPyTorch":arr_agreements,"maximumLogitAbsoluteError":max_error,"packageBytes":sum(p.stat().st_size for p in package.rglob("*") if p.is_file()),"predictionSeconds":time.perf_counter()-started,"platform":platform.platform(),"computeUnits":"ALL; device placement not measured; not proof of ANE residency","iPhoneTested":False,"classCorrect":sum(p["expected"]==p["predicted"] for p in predictions),"testCorrect":sum(p["expected"]==p["predicted"] for p in predictions if p["split"]=="test"),"testSamples":sum(p["split"]=="test" for p in predictions)}
    write(root/"coreml-verification.json",summary)
    # Changes in argmax require explicit investigation, not silently shipping it.
    assert agreements==len(rows) and arr_agreements==len(rows), summary
    shutil.copy2(Path(args.base)/"NOTICE.txt",root/"NOTICE.txt")
    write(root/"deployment-manifest.json",{"status":"development-candidate","checkpointSha256":digest(root/"best.pt"),"datasetSha256":digest(args.dataset),"baseRevision":config["revision"],"tokenizerDirectory":"tokenizer","coreMLPackage":package.name,"sourceImageUpload":False,"runtimeNetworkRequired":False,"productionModelReplaced":False})
    print(json.dumps(summary,indent=2),flush=True)


if __name__=="__main__": main()
